import { generateTokens } from "../css/1-tokens/tokens.js";
import { themes } from "../css/1-tokens/themes.js";
import fs from "fs";

Object.entries(themes).forEach(([themeName, theme]) => {
  const tokens = generateTokens(theme);
  const scss = `
// DO NOT EDIT THIS FILE DIRECTLY.
// Update it by running "npm run themes:generate"
@use './app';

:root {
  ${Object.entries(tokens)
    .map(([name, value]) => `--${name}: ${value}`)
    .join(";\n  ")}
};

`;

  fs.writeFileSync(`./css/app.${themeName}.scss`, scss);
});
